### ISSUE TITLE
Error with Unity version 2021.3.10f1

### ISSUE THREAD

**Issue by ghost** [Ending2015a/kage#2]
The shader you developed works great in Scene view, but it gives me some troubles in Game view.

I'm trying to overlap a 3d model, with shadows, to a background image imported in Canvas as a Raw Image. Of course, I don't want the plane where the shadow is received to be visible, so that I get the effect of my object casting shadow directly on the background.
However, with this shader, the plane is still visible by the camera, and I see the whole plane overlapped to the background.

I provide a sample project to reproduce my issue (I can't provide the original project since I signed an NDA):

[https://github.com/frettore/ErrorSample](url)

**Comment by Ending2015a** [comment]
Hello @frettore,
Thank you for reporting the issue. I can confirm this issue from your sample project.
I think the problem is caused by the rendering order of the canvas and the shadow plane.
Because in default the canvas is rendered after the shadow plane is done. The rendering procedure would be like:
1. Draw the shadow plane. Alpha blend with background color.
2. Draw the canvas. This will not trigger alpha blending, because the canvas is behind the shadow plane.

The solution is to switch the rendering order of the canvas and the shadow plane:
1. Create a material named "UIMat" or whatever.
4. Set the render queue of "UIMat" to "Geometry" or "2000"
5. Apply it to your "RawImage" game object
6. If this still not work, try to change the render queue of the shadow plane to "2500".

Another solution is to use the 3D plane or quad instead of UI canvas.

Left: before
Right: after
![Screenshot from 2022-11-09 22-38-29](https://user-images.githubusercontent.com/18180004/200860850-454e6bad-604d-462d-8600-9f9ba0bb9cf3.png)

**Comment by ghost** [comment]
Thank you very much @Ending2015a !!!!!

That was exactly the problem and now everything works perfectly. You literally prevented me from getting mad!
